In [1]:
print("hey! let's explore Machine Learning.")

hey! let's explore Machine Learning.


In [9]:
#numpy: numerical python library
import numpy as np
list =[1,2,3,4,5]
arr=np.array(list)
arr

array([1, 2, 3, 4, 5])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
np.random.randint(0,10)

np.random.randint(0,10,(4,4))

array([[2, 6, 2, 2],
       [8, 1, 3, 2],
       [0, 3, 0, 7],
       [0, 2, 8, 0]])

In [145]:
np.random.seed(101)
arr=np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [148]:
np.random.seed(101)
arr=np.random.randint(0,100,10)
arr
arr.max()
arr.min()
arr.mean()
arr.argmax()
arr.argmin()
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [152]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[2,2] 
mat[:,0] #accessing first column
mat[0,:] #accessing first row
mat[0:3,0:3] #accessing first three row and column

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])